//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA.Entities.Administrador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
    
        public int CodigoUsuario { get; set; }
        public string IdentificadorUsuario { get; set; }
        public string CorreoElectronico { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<bool> IndicadorPrimerIngreso { get; set; }
        public Nullable<bool> IndicadorRecuperacionPassword { get; set; }
        public Nullable<System.DateTime> FechaUltimoAcceso { get; set; }
        public string CodigoEstadoUsuario { get; set; }
        public Nullable<short> CantidadIntentos { get; set; }
        public Nullable<int> UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> UsuarioUltimaModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<short> CodigoSponsorPrincipal { get; set; }
        public Nullable<int> CodigoFuncionario { get; set; }
        public string NombreFuncionario { get; set; }
        public Nullable<int> CodigoAgencia { get; set; }
        public string NombreAgencia { get; set; }
        public Int16 Perfil { get; set; }
        public string Clave { get; set; }

        public int CodTipoDocumento { get; set; }

        public string NumeroDocumento { get; set; }

        public int CodCargo { get; set; }

        public string NombreBusqueda { get; set; }




    }
}
